export const categorias = [
    "Livros",
    "Brinquedos",
    "Roupas",
    "Eletrônicos",
    "Decoração",
    "Calçados",
    "Esportes",
    "Acessórios",
    "Cozinha",
    "Papelaria",
    "Instrumentos",
    "Pets",
    "Outros",
];
