export const itensDisponiveis = [
  {
    id: 1,
    titulo: "Livros de Romance",
    descricao:
      "Coleção de 15 livros de romance em ótimo estado. Inclui autores como Nicholas Sparks, Jojo Moyes, e outros.",
    categoria: "Livros",
    usuario: "Maria Silva",
    bairro: "Centro",
    dataPublicacao: "2 dias atrás",
    imagem: "/placeholder.svg?height=300&width=400",
    status: "disponivel",
    likes: 12,
    rating: 4.8,
    condicao: "Ótimo estado",
    observacoes: "Prefiro trocar por itens de casa ou decoração. Disponível para encontro nos finais de semana.",
  },
  {
    id: 2,
    titulo: "Bicicleta Infantil",
    descricao: "Bicicleta aro 16, cor azul, pouco usada",
    categoria: "Brinquedos",
    usuario: "João Santos",
    bairro: "Vila Nova",
    dataPublicacao: "1 dia atrás",
    imagem: "/placeholder.svg?height=300&width=400",
    status: "disponivel",
    likes: 8,
    rating: 4.9,
    condicao: "Bom estado",
    observacoes: "Criança cresceu e não usa mais. Aceito trocas por livros infantis.",
  },
  {
    id: 3,
    titulo: "Roupas Femininas Tam M",
    descricao: "Lote com 10 peças de roupas femininas tamanho M",
    categoria: "Roupas",
    usuario: "Ana Costa",
    bairro: "Jardim das Flores",
    dataPublicacao: "3 dias atrás",
    imagem: "/placeholder.svg?height=300&width=400",
    status: "disponivel",
    likes: 15,
    rating: 4.7,
    condicao: "Ótimo estado",
    observacoes: "Roupas pouco usadas, algumas ainda com etiqueta.",
  },
  {
    id: 4,
    titulo: "Kit Ferramentas Básicas",
    descricao: "Martelo, chaves de fenda, alicate e outras ferramentas",
    categoria: "Ferramentas",
    usuario: "Carlos Oliveira",
    bairro: "Centro",
    dataPublicacao: "5 dias atrás",
    imagem: "/placeholder.svg?height=300&width=400",
    status: "disponivel",
    likes: 6,
    rating: 4.6,
    condicao: "Bom estado",
    observacoes: "Ferramentas funcionais, algumas com sinais de uso.",
  },
  {
    id: 5,
    titulo: "Jogos de Tabuleiro",
    descricao: "War, Banco Imobiliário e Detetive - todos completos",
    categoria: "Brinquedos",
    usuario: "Fernanda Lima",
    bairro: "Vila Nova",
    dataPublicacao: "1 semana atrás",
    imagem: "/placeholder.svg?height=300&width=400",
    status: "disponivel",
    likes: 20,
    rating: 5.0,
    condicao: "Ótimo estado",
    observacoes: "Jogos completos, bem conservados. Aceito trocas por livros ou eletrônicos.",
  },
  {
    id: 6,
    titulo: "Panelas de Inox",
    descricao: "Conjunto de 5 panelas de inox em bom estado",
    categoria: "Casa",
    usuario: "Roberto Mendes",
    bairro: "Jardim das Flores",
    dataPublicacao: "4 dias atrás",
    imagem: "/placeholder.svg?height=300&width=400",
    status: "disponivel",
    likes: 9,
    rating: 4.5,
    condicao: "Bom estado",
    observacoes: "Panelas funcionais, algumas com pequenos riscos de uso.",
  },
]

export const propostasRecebidas = [
  {
    id: 1,
    itemSolicitado: "Livros de Romance",
    itemOferecido: "Conjunto de Panelas",
    usuario: "Roberto Mendes",
    bairro: "Jardim das Flores",
    data: "2 dias atrás",
    status: "pendente",
    mensagem: "Olá! Tenho interesse nos seus livros. Posso oferecer um conjunto de panelas de inox em ótimo estado.",
    chatId: "chat_1",
  },
  {
    id: 2,
    itemSolicitado: "Livros de Romance",
    itemOferecido: "Roupas Femininas",
    usuario: "Ana Costa",
    bairro: "Jardim das Flores",
    data: "1 dia atrás",
    status: "pendente",
    mensagem: "Oi! Gostaria de trocar por algumas roupas femininas tamanho M. Você teria interesse?",
    chatId: "chat_2",
  },
]

export const propostasEnviadas = [
  {
    id: 3,
    itemSolicitado: "Bicicleta Infantil",
    itemOferecido: "Jogos de Tabuleiro",
    usuario: "João Santos",
    bairro: "Vila Nova",
    data: "3 dias atrás",
    status: "aceita",
    mensagem: "Tenho jogos de tabuleiro completos para trocar pela bicicleta.",
    chatId: "chat_3",
  },
  {
    id: 4,
    itemSolicitado: "Kit Ferramentas",
    itemOferecido: "Livros Técnicos",
    usuario: "Carlos Oliveira",
    bairro: "Centro",
    data: "5 dias atrás",
    status: "recusada",
    mensagem: "Posso oferecer livros técnicos de engenharia.",
    chatId: "chat_4",
  },
]

export const conversas = [
  {
    id: "chat_1",
    propostaId: 1,
    participantes: ["Maria Silva", "Roberto Mendes"],
    mensagens: [
      {
        id: 1,
        autor: "Roberto Mendes",
        mensagem:
          "Olá! Tenho interesse nos seus livros. Posso oferecer um conjunto de panelas de inox em ótimo estado.",
        timestamp: "2024-01-15T10:30:00Z",
        tipo: "proposta",
      },
      {
        id: 2,
        autor: "Maria Silva",
        mensagem: "Oi Roberto! Que legal! Pode me contar mais sobre as panelas? Quantas são e qual o tamanho?",
        timestamp: "2024-01-15T14:20:00Z",
        tipo: "resposta",
      },
      {
        id: 3,
        autor: "Roberto Mendes",
        mensagem:
          "São 5 panelas: 2 pequenas, 2 médias e 1 grande. Todas de inox, bem conservadas. Posso mandar fotos se quiser!",
        timestamp: "2024-01-15T15:45:00Z",
        tipo: "resposta",
      },
      {
        id: 4,
        autor: "Maria Silva",
        mensagem: "Perfeito! Adoraria ver as fotos. E onde podemos nos encontrar para fazer a troca?",
        timestamp: "2024-01-15T16:10:00Z",
        tipo: "resposta",
      },
    ],
    ultimaAtividade: "2024-01-15T16:10:00Z",
    status: "ativa",
  },
  {
    id: "chat_2",
    propostaId: 2,
    participantes: ["Maria Silva", "Ana Costa"],
    mensagens: [
      {
        id: 1,
        autor: "Ana Costa",
        mensagem: "Oi! Gostaria de trocar por algumas roupas femininas tamanho M. Você teria interesse?",
        timestamp: "2024-01-16T09:15:00Z",
        tipo: "proposta",
      },
      {
        id: 2,
        autor: "Maria Silva",
        mensagem: "Oi Ana! Que tipo de roupas você tem? Estou procurando mais roupas casuais.",
        timestamp: "2024-01-16T11:30:00Z",
        tipo: "resposta",
      },
    ],
    ultimaAtividade: "2024-01-16T11:30:00Z",
    status: "ativa",
  },
]

export const categorias = ["Todas", "Livros", "Roupas", "Brinquedos", "Ferramentas", "Casa", "Eletrônicos"]

export const bairros = ["Centro", "Vila Nova", "Jardim das Flores", "Bela Vista", "São José", "Outros"]

export const meusItens = [
  { id: 1, titulo: "Conjunto de Panelas", categoria: "Casa" },
  { id: 2, titulo: "Jogos de Tabuleiro", categoria: "Brinquedos" },
  { id: 3, titulo: "Roupas Masculinas", categoria: "Roupas" },
]
